version: '3'
services:
  web:
    image: nginx:latest
    container_name: webserver
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php
      - db

  php:
    build: ./php
    container_name: php-fpm
    volumes:
      - ./app:/var/www/html

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
